- name: configuring backend server
  hosts: backend
  become: yes
  tasks:
    - name: Enable Node.js 20 DNF module stream
      command: dnf module enable nodejs:20 -y
    - name: Install nodejs
      package:
        name: nodejs
        state: present
    - name: remove app directory if already exist
      file:
        path: /app
        state: absent
    - name: create app direcotory
      file:
        path: /app
        state: directory
    - name: Create a dedicated system user for the application
      ansible.builtin.user:
        name: expense
        comment: "expense system user"
        system: yes
        shell: /sbin/nologin
        home: /app
        state: present
    - name: Ensure tar and python driver are installed
      ansible.builtin.package:
        name:
          - tar
        state: present
    - name: Download and unzip application code
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/daws-90s/expense-documentation/refs/heads/main/artifacts/expense-backend-v3.tar.gz
        dest: /app
        remote_src: yes
    - name: Install Node.js application dependencies
      community.general.npm:
        path: /app
        state: present
    - name: Copy and configure application environment file
      template:
        src: nodejs.conf.j2
        dest: /etc/systemd/system/backend.service
    - name: Reload systemd configuration cache to register new backend service
      ansible.builtin.systemd:
        daemon_reload: true
    - name: install mysql client
      package:
        name: mysql
        state: present
    - name: Ensure python3-pip is available on backend host
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install PyMySQL driver using pip3
      ansible.builtin.pip:
        name: pymysql
        state: present

    - name: Ensure the transactions database exists
      community.mysql.mysql_db:
        login_host: database.yokshithkumar.shop
        login_user: root
        login_password: "{{ mysql_password }}"
        name: transactions
        state: present

    - name: Check if the transaction table exists inside the transactions database
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_db: information_schema
        query: |
          SELECT TABLE_NAME 
          FROM TABLES 
          WHERE TABLE_SCHEMA = 'transactions' 
            AND TABLE_NAME = 'transaction';
      register: schema_check

    - name: Ensure the transactions database is physically created
      community.mysql.mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        name: transactions
        state: present
      when: schema_check.query_result[0] | length == 0

    - name: Load the data schema because database or table was missing
      community.mysql.mysql_db:
        state: import
        name: transactions
        target: "/app/schema/backend.sql" # Ensure this path points to your SQL file
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
      when: schema_check.query_result[0] | length == 0
