- name: configuring database servers
  hosts: database
  become: yes
  tasks:
    - name: installing mysql package
      package:
        name: mysql-server
        state: present
    - name: enable and start the mysql server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true

    
    - name: setup root user_password
      ansible.builtin.shell: |
        mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'ExpenseApp@1';"
      register: result
      failed_when: 
        - result.rc != 0 
        - "'ERROR 1045' not in result.stderr" # Don't fail if the password was already changed
      changed_when: result.rc == 0
         