- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: enable nginx 1.24
    command: dnf module enable nginx:1.24 -y
  - name: install nginx
    package:
      name: nginx
      state: present
  - name: copy nginx conf
    template:
      src: lb.conf.j2
      dest: /etc/nginx/nginx.conf
  - name: restart and enable frontend
    service:
      name: nginx
      state: started
      enabled: yes